import { Button, ScrollView } from "std-widgets.slint";

component Btn inherits Button {
    width: 150px;
}

component Lis inherits VerticalLayout {
    in property <[string]> items;
    // -1 means no selection
    in-out property <int> selected-index: -1;

    spacing: 4px;

    ScrollView {
        height: 100%;
        viewport-height: (root.items.length * 25px);

        VerticalLayout {
            alignment: start;
            for path[i] in root.items : Rectangle {
                height: 25px;

                // Visual Highlight Logic
                background: root.selected-index == i ? #cccccc : transparent;

                // Click handler for the row
                TouchArea {
                    clicked => {
                        root.selected-index = i;
                    }
                }

                Text {
                    text: path;
                    color: green;
                    horizontal-alignment: center;
                    vertical-alignment: center;
                    overflow: elide;
                }
            }
        }
    }
}

export component MainWindow inherits Window {
    width: 800px;
    height: 400px;

    callback pick-file();
    callback create-zip();

    callback remove-item(int);

    in-out property <[string]> file-list: [];

    VerticalLayout {
        alignment: center;
        spacing: 10px;

        Text {
            text: "Selected Files:";
            font-size: 16px;
            horizontal-alignment: center;
        }

        // Give the list an ID (list-view) so we can read its 'selected-index'
        list-view := Lis {
            items: root.file-list;
            height: 150px;
        }

        Btn {
            text: "Add";
            clicked => { root.pick-file(); }
        }

        Btn {
            text: "Remove";
            // Disable button if nothing is selected (-1)
            enabled: list-view.selected-index != -1;

            clicked => {
                root.remove-item(list-view.selected-index);
                // Reset selection
                list-view.selected-index = -1;
            }
        }

        Btn {
            text: "Create .zip archive";
            clicked => { root.create-zip(); }
        }
    }
}
